name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.19", "1.18", "1.17"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run mod-check
        run: make mod-check

      - name: Run tests
        run: make test

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
